"""
ScopeForge — FastAPI application entry point.

Run with:
    uvicorn main:app --reload --port 8000
"""

from __future__ import annotations

import logging
from typing import Optional

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse

from schema import ProjectScope
from parser import extract_text_from_upload
from llm import generate_scope
from exporter import build_docx

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s  %(message)s",
)
logger = logging.getLogger(__name__)

# ── App ───────────────────────────────────────────────────────────────────────
app = FastAPI(
    title="ScopeForge API",
    description="Turns messy client notes into structured project-scope documents.",
    version="1.0.0",
)

# ── CORS ──────────────────────────────────────────────────────────────────────
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Health check ──────────────────────────────────────────────────────────────
@app.get("/health")
async def health_check():
    return {"status": "ok"}


# ── POST /generate-scope ─────────────────────────────────────────────────────
@app.post("/generate-scope", response_model=ProjectScope)
async def generate_scope_endpoint(
    text: Optional[str] = Form(None),
    file: Optional[UploadFile] = File(None),
):
    """Accept client notes (as raw text or an uploaded file) and return a
    structured project scope generated by the LLM.
    """

    # 1. Resolve input text
    client_notes: str = ""

    if file and file.filename:
        logger.info("Received file upload: %s", file.filename)
        client_notes = await extract_text_from_upload(file)
    elif text and text.strip():
        client_notes = text.strip()

    if not client_notes:
        raise HTTPException(
            status_code=400,
            detail="No input provided. Please either paste text or upload a "
                   ".docx / .pdf / .txt file.",
        )

    logger.info(
        "Processing client notes (%d characters)…", len(client_notes)
    )

    # 2. Call the LLM
    try:
        scope = await generate_scope(client_notes)
    except RuntimeError as exc:
        # Missing API key or client init errors
        logger.error("Configuration error: %s", exc)
        raise HTTPException(status_code=500, detail=str(exc))
    except ValueError as exc:
        # LLM returned unparseable / invalid output after retries
        logger.error("LLM output error: %s", exc)
        raise HTTPException(
            status_code=502,
            detail=f"The AI service returned an invalid response. {exc}",
        )
    except Exception as exc:
        logger.exception("Unexpected error during scope generation")
        raise HTTPException(
            status_code=500,
            detail=f"An unexpected error occurred while generating the scope: {exc}",
        )

    return scope


# ── POST /export-docx ────────────────────────────────────────────────────────
@app.post("/export-docx")
async def export_docx_endpoint(scope: ProjectScope):
    """Accept a structured scope JSON body and return a formatted Word
    document as a downloadable file.
    """
    try:
        buffer = build_docx(scope)
    except Exception as exc:
        logger.exception("Error building Word document")
        raise HTTPException(
            status_code=500,
            detail=f"Failed to generate the Word document: {exc}",
        )

    return StreamingResponse(
        buffer,
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={
            "Content-Disposition": 'attachment; filename="scope_doc.docx"'
        },
    )
